### ISSUE TITLE
http -> https

### ISSUE THREAD

**Issue by MattHJensen** [comp-org/comp#4]
www.compmodels.com should accommodate http**s**.

**Comment by hdoupe** [comment]
Agreed. I'm working on this.

**Comment by MattHJensen** [comment]
Expeditedssl looks good to me. We could get "single" and upgrade to "wildcard" when we/if want to use subdomains. 
https://elements.heroku.com/addons/expeditedssl

**Comment by hdoupe** [comment]
I'm also onboard. There's a nice video guide too: https://www.youtube.com/watch?v=OcyR7Yus4pc

I can go ahead with the heroku add on. It looks like there will be a step on the godaddy side that you have to do though.

**Comment by hdoupe** [comment]
Looks like https://www.compmodels.com/ is working.

There are some settings on the django end to enforce the https requirement. Once those are updated, this issue should be resolved.

**Comment by hdoupe** [comment]
Resolved. Thanks for kick-starting the process @MattHJensen
