### ISSUE TITLE
Tax-Brain sensitive data file

### ISSUE THREAD

**Issue by hdoupe** [comp-org/comp#96]
PSLmodels/Tax-Brain can be run with two files: a less accurate but public file and a more accurate but private file. This issue proposes an approach for giving COMP access to the private file. 

The private file can be stored in a S3 bucket which is under the Open Source Policy Center's AWS account. Then, the Open Source Policy Center would give COMP read access to this account using a similar approach to [how PaperTrail handles storing log data in an S3 bucket of the owner's choosing](https://help.papertrailapp.com/kb/how-it-works/automatic-s3-archive-export/#create-and-share-an-s3-bucket). On each simulation, COMP would read the data like this:

```python
import gzip
import boto3
import pandas as pd

client = boto3.client(
    "s3", 
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key
)
obj = client.get_object(Bucket='bucket-name', Key='path/to/file.csv')
gz = gzip.GzipFile(fileobj=obj['Body'])
data = pd.read_csv(gz)
```

Note that the sensitive data is never stored and is streamed directly to a pandas dataframe. Alternatively, the data stream could be passed directly to Tax-Brain and Tax-Brain could handle loading it into a pandas dataframe.

This data can then be passed to Tax-Brain in the simulation function like this:

```
    import taxbrain

    def run(start_year, data_source, use_full_sample, user_mods, puf_file):
        return taxbrain.tbi.run_tbi_model(
            start_year, data_source, use_full_sample, user_mods, puf_file
        )
```

@andersonfrailey and @MattHJensen what do you think about this approach?

**Comment by andersonfrailey** [comment]
@hdoupe seems straightforward enough. From a Tax-Brain perspective, I'm indifferent to being passed a DataFrame or simply a path to read the file as a DataFrame.
